### ISSUE TITLE
Expose Put Card in REST API

### ISSUE THREAD

**Issue by sudobob** [uhppoted/uhppoted-rest#1]
Put Card appears to be implemented in the core but not the rest API. Any plans to implement that ?

**Comment by uhppoted** [comment]
I seem to remember it was left out of the REST API because the thinking at that point in time was that access control lists were going to be the way to manage cards.

However, that was **way** back when and everything has changed (as usual :-)) .. I'll add it in - give me a couple of days?

**Comment by sudobob** [comment]
Thank you very much. I have another question; Has anyone implemented a web front end ?

**Comment by uhppoted** [comment]
Hi,

I've pushed a preliminary implementation of the `PutCard` API to the `master` branch - the updated OpenAPI spec is here: [uhppoted-rest-api](https://github.com/uhppoted/uhppoted/blob/master/documentation/openapi/uhppoted-api.yaml). Let me know if you find any problems with it.

I think I'm going take this opportunity to clean up the internal implementation a bit so am going to hold off on creating a release for it (and the API's _may_ change a little. It's unlikely but ..) - if that's a problem for you let me know and I'll split up the work into separate releases. 

**re. web front end**. Not as far as I know - the one person who was chatting to me about creating one then got very work busy so it went into limbo. Am planning to start work on user interfaces starting with the 0.7.x versions (so probably early June'ish) - am taking suggestions and feature requests though :-).

**Comment by uhppoted** [comment]
Provisionally fixed in _master_ branch - pending release v0.6.2.

**Comment by uhppoted** [comment]
Implemented in release v0.6.2
