### ISSUE TITLE
Migrate to uhppoted-lib log

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-rest#4]
_uhppoted-rest_ is currently using a mix of `fmt.Printf` and `log.Logger` for logging - replace throughout with the _uhppoted-lib_ log package for consistency and to simplify future maintenance.

- [x] Update _uhppoted-rest_
- [x] Update _uhppoted-lib_ `healthcheck` and `watchdog`
- [x] Update _uhppoted-mqtt_ for reworked  `healthcheck` and `watchdog`
- [x] Check daemonized logging

**Comment by twystd** [comment]
Migration to uhppoted-lib logging complete - pending release v0.8.4
